<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'WicketAcc\\Admin\\' => array($baseDir . '/src/admin'),
    'WicketAcc\\' => array($baseDir . '/src'),
);
