<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit853244f2e24b990fff247782c5efec39
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WicketAcc\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WicketAcc\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit853244f2e24b990fff247782c5efec39', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WicketAcc\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit853244f2e24b990fff247782c5efec39', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WicketAcc\Composer\Autoload\ComposerStaticInit853244f2e24b990fff247782c5efec39::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
