<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WicketAcc\\Account' => $baseDir . '/src/Account.php',
    'WicketAcc\\Admin\\AdminSettings' => $baseDir . '/src/admin/AdminSettings.php',
    'WicketAcc\\Admin\\WicketAccSafeguard' => $baseDir . '/src/admin/WicketAccSafeguard.php',
    'WicketAcc\\Assets' => $baseDir . '/src/Assets.php',
    'WicketAcc\\Blocks' => $baseDir . '/src/Blocks.php',
    'WicketAcc\\Helpers' => $baseDir . '/src/Helpers.php',
    'WicketAcc\\Language' => $baseDir . '/src/Language.php',
    'WicketAcc\\MdpApi' => $baseDir . '/src/MdpApi.php',
    'WicketAcc\\MethodRouter' => $baseDir . '/src/MethodRouter.php',
    'WicketAcc\\OrganizationProfile' => $baseDir . '/src/OrganizationProfile.php',
    'WicketAcc\\Profile' => $baseDir . '/src/Profile.php',
    'WicketAcc\\Registers' => $baseDir . '/src/Registers.php',
    'WicketAcc\\Router' => $baseDir . '/src/Router.php',
    'WicketAcc\\Shortcodes' => $baseDir . '/src/Shortcodes.php',
    'WicketAcc\\User' => $baseDir . '/src/User.php',
    'WicketAcc\\WooCommerce' => $baseDir . '/src/WooCommerce.php',
);
