<?php

// autoload_static.php @generated by Composer

namespace WicketAcc\Composer\Autoload;

class ComposerStaticInit853244f2e24b990fff247782c5efec39
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WicketAcc\\Admin\\' => 16,
            'WicketAcc\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WicketAcc\\Admin\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/admin',
        ),
        'WicketAcc\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WicketAcc\\Account' => __DIR__ . '/../..' . '/src/Account.php',
        'WicketAcc\\Admin\\AdminSettings' => __DIR__ . '/../..' . '/src/admin/AdminSettings.php',
        'WicketAcc\\Admin\\WicketAccSafeguard' => __DIR__ . '/../..' . '/src/admin/WicketAccSafeguard.php',
        'WicketAcc\\Assets' => __DIR__ . '/../..' . '/src/Assets.php',
        'WicketAcc\\Blocks' => __DIR__ . '/../..' . '/src/Blocks.php',
        'WicketAcc\\Helpers' => __DIR__ . '/../..' . '/src/Helpers.php',
        'WicketAcc\\Language' => __DIR__ . '/../..' . '/src/Language.php',
        'WicketAcc\\MdpApi' => __DIR__ . '/../..' . '/src/MdpApi.php',
        'WicketAcc\\MethodRouter' => __DIR__ . '/../..' . '/src/MethodRouter.php',
        'WicketAcc\\OrganizationProfile' => __DIR__ . '/../..' . '/src/OrganizationProfile.php',
        'WicketAcc\\Profile' => __DIR__ . '/../..' . '/src/Profile.php',
        'WicketAcc\\Registers' => __DIR__ . '/../..' . '/src/Registers.php',
        'WicketAcc\\Router' => __DIR__ . '/../..' . '/src/Router.php',
        'WicketAcc\\Shortcodes' => __DIR__ . '/../..' . '/src/Shortcodes.php',
        'WicketAcc\\User' => __DIR__ . '/../..' . '/src/User.php',
        'WicketAcc\\WooCommerce' => __DIR__ . '/../..' . '/src/WooCommerce.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit853244f2e24b990fff247782c5efec39::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit853244f2e24b990fff247782c5efec39::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit853244f2e24b990fff247782c5efec39::$classMap;

        }, null, ClassLoader::class);
    }
}
