<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'voku\\' => array($vendorDir . '/voku/portable-ascii/src/voku'),
    'WicketAcc\\Wicket\\' => array($vendorDir . '/industrialdev/wicket-sdk-php/src'),
    'WicketAcc\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'WicketAcc\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'WicketAcc\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'WicketAcc\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'WicketAcc\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'WicketAcc\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'WicketAcc\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'WicketAcc\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'WicketAcc\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'WicketAcc\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/support', $vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/macroable', $vendorDir . '/illuminate/conditionable'),
    'WicketAcc\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'WicketAcc\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'WicketAcc\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'WicketAcc\\Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'WicketAcc\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib/Doctrine/Inflector'),
    'WicketAcc\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'WicketAcc\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'WicketAcc\\Admin\\' => array($baseDir . '/src/admin'),
    'WicketAcc\\' => array($baseDir . '/src'),
    'Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
);
