<?php

// autoload_static.php @generated by Composer

namespace HMApi\Composer\Autoload;

class ComposerStaticInitc0e3399e672c61366037eb22a5860f68
{
    public static $files = array (
        '765877c22806cd3aae73f7162b2a69d7' => __DIR__ . '/..' . '/adbario/php-dot-notation/src/helpers.php',
        '09cf3936aa2ba06d40dd63bf48b69aca' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/helpers.php',
        '16384c332de4c1779a45fa95a6930f09' => __DIR__ . '/../..' . '/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'HMApi\\starfederation\\datastar\\' => 30,
            'HMApi\\Jeffreyvr\\WPSettings\\' => 27,
            'HMApi\\Adbar\\' => 12,
            'HMApi\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'HMApi\\starfederation\\datastar\\' => 
        array (
            0 => __DIR__ . '/..' . '/starfederation/datastar-php/src',
        ),
        'HMApi\\Jeffreyvr\\WPSettings\\' => 
        array (
            0 => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src',
        ),
        'HMApi\\Adbar\\' => 
        array (
            0 => __DIR__ . '/..' . '/adbario/php-dot-notation/src',
        ),
        'HMApi\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'ComposerAutoloaderInitc0e3399e672c61366037eb22a5860f68' => __DIR__ . '/..' . '/composer/autoload_real.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'HMApi\\Adbar\\Dot' => __DIR__ . '/..' . '/adbario/php-dot-notation/src/Dot.php',
        'HMApi\\Admin\\Activation' => __DIR__ . '/../..' . '/src/Admin/Activation.php',
        'HMApi\\Admin\\Options' => __DIR__ . '/../..' . '/src/Admin/Options.php',
        'HMApi\\Admin\\WPSettingsOptions' => __DIR__ . '/../..' . '/src/Admin/WPSettingsOptions.php',
        'HMApi\\Assets' => __DIR__ . '/../..' . '/src/Assets.php',
        'HMApi\\Compatibility' => __DIR__ . '/../..' . '/src/Compatibility.php',
        'HMApi\\Composer\\Autoload\\ClassLoader' => __DIR__ . '/..' . '/composer/ClassLoader.php',
        'HMApi\\Composer\\Autoload\\ComposerStaticInitc0e3399e672c61366037eb22a5860f68' => __DIR__ . '/..' . '/composer/autoload_static.php',
        'HMApi\\Config' => __DIR__ . '/../..' . '/src/Config.php',
        'HMApi\\Jeffreyvr\\WPSettings\\EnqueueManager' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/EnqueueManager.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Enqueuer' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Enqueuer.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Error' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Error.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Flash' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Flash.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Option' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Option.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Checkbox' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Checkbox.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Choices' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Choices.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\CodeEditor' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/CodeEditor.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Color' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Color.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Image' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Image.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Media' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Media.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\OptionAbstract' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/OptionAbstract.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Select' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Select.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\SelectMultiple' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/SelectMultiple.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Text' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Text.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Textarea' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Textarea.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\Video' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/Video.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Options\\WPEditor' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Options/WPEditor.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Section' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Section.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Tab' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Tab.php',
        'HMApi\\Jeffreyvr\\WPSettings\\Traits\\HasOptionLevel' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/Traits/HasOptionLevel.php',
        'HMApi\\Jeffreyvr\\WPSettings\\WPSettings' => __DIR__ . '/..' . '/jeffreyvanrossum/wp-settings/src/WPSettings.php',
        'HMApi\\Libraries\\AlpineAjaxLib' => __DIR__ . '/../..' . '/src/Libraries/AlpineAjaxLib.php',
        'HMApi\\Libraries\\DatastarLib' => __DIR__ . '/../..' . '/src/Libraries/DatastarLib.php',
        'HMApi\\Libraries\\HTMXLib' => __DIR__ . '/../..' . '/src/Libraries/HTMXLib.php',
        'HMApi\\Main' => __DIR__ . '/../..' . '/src/Main.php',
        'HMApi\\Render' => __DIR__ . '/../..' . '/src/Render.php',
        'HMApi\\Router' => __DIR__ . '/../..' . '/src/Router.php',
        'HMApi\\Theme' => __DIR__ . '/../..' . '/src/Theme.php',
        'HMApi\\starfederation\\datastar\\Consts' => __DIR__ . '/..' . '/starfederation/datastar-php/src/Consts.php',
        'HMApi\\starfederation\\datastar\\ServerSentEventData' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventData.php',
        'HMApi\\starfederation\\datastar\\ServerSentEventGenerator' => __DIR__ . '/..' . '/starfederation/datastar-php/src/ServerSentEventGenerator.php',
        'HMApi\\starfederation\\datastar\\enums\\ElementPatchMode' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/ElementPatchMode.php',
        'HMApi\\starfederation\\datastar\\enums\\EventType' => __DIR__ . '/..' . '/starfederation/datastar-php/src/enums/EventType.php',
        'HMApi\\starfederation\\datastar\\events\\EventInterface' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventInterface.php',
        'HMApi\\starfederation\\datastar\\events\\EventTrait' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/EventTrait.php',
        'HMApi\\starfederation\\datastar\\events\\ExecuteScript' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/ExecuteScript.php',
        'HMApi\\starfederation\\datastar\\events\\Location' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/Location.php',
        'HMApi\\starfederation\\datastar\\events\\PatchElements' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/PatchElements.php',
        'HMApi\\starfederation\\datastar\\events\\PatchSignals' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/PatchSignals.php',
        'HMApi\\starfederation\\datastar\\events\\RemoveElements' => __DIR__ . '/..' . '/starfederation/datastar-php/src/events/RemoveElements.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc0e3399e672c61366037eb22a5860f68::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc0e3399e672c61366037eb22a5860f68::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc0e3399e672c61366037eb22a5860f68::$classMap;

        }, null, ClassLoader::class);
    }
}
