<?php

// autoload_real.php @generated by Composer

class WicketAcc_ComposerAutoloaderInitc0e3399e672c61366037eb22a5860f68
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('HMApi\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \HMApi\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('WicketAcc_ComposerAutoloaderInitc0e3399e672c61366037eb22a5860f68', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \HMApi\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('WicketAcc_ComposerAutoloaderInitc0e3399e672c61366037eb22a5860f68', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\HMApi\Composer\Autoload\ComposerStaticInitc0e3399e672c61366037eb22a5860f68::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \HMApi\Composer\Autoload\ComposerStaticInitc0e3399e672c61366037eb22a5860f68::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
