<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitd76a2a1babd2917c8a3ce489b49ec6a0
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WicketAcc\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WicketAcc\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitd76a2a1babd2917c8a3ce489b49ec6a0', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WicketAcc\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitd76a2a1babd2917c8a3ce489b49ec6a0', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WicketAcc\Composer\Autoload\ComposerStaticInitd76a2a1babd2917c8a3ce489b49ec6a0::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \WicketAcc\Composer\Autoload\ComposerStaticInitd76a2a1babd2917c8a3ce489b49ec6a0::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
