<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    '68b4fe79160f6d3cf61ecdf7d7bc06bc' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'a905f042d7b8a2fa6f1e42d752744f1f' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    'e5c7c9f11db8ea6b2d24af61817f0b72' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    '7730ef334e56b88926f09b62b30f8fd7' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    'd363caba7e9dae99102c74b5dd61f7ec' => $vendorDir . '/symfony/translation/Resources/functions.php',
    'b2fdce20cb0f05630859c19a9bf17c95' => $vendorDir . '/illuminate/collections/helpers.php',
    'cc42e32ef0c367b92176a7e66435cd58' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    '16c9ca11085e531b6b8a5ab1fbfa5657' => $vendorDir . '/illuminate/support/helpers.php',
];
