<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return [
    'voku\\' => [$vendorDir . '/voku/portable-ascii/src/voku'],
    'WicketAcc\\Wicket\\' => [$vendorDir . '/industrialdev/wicket-sdk-php/src'],
    'WicketAcc\\Symfony\\Polyfill\\Php80\\' => [$vendorDir . '/symfony/polyfill-php80'],
    'WicketAcc\\Symfony\\Polyfill\\Mbstring\\' => [$vendorDir . '/symfony/polyfill-mbstring'],
    'WicketAcc\\Symfony\\Contracts\\Translation\\' => [$vendorDir . '/symfony/translation-contracts'],
    'WicketAcc\\Symfony\\Component\\Translation\\' => [$vendorDir . '/symfony/translation'],
    'WicketAcc\\Psr\\SimpleCache\\' => [$vendorDir . '/psr/simple-cache/src'],
    'WicketAcc\\Psr\\Http\\Message\\' => [$vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'],
    'WicketAcc\\Psr\\Http\\Client\\' => [$vendorDir . '/psr/http-client/src'],
    'WicketAcc\\Psr\\Container\\' => [$vendorDir . '/psr/container/src'],
    'WicketAcc\\Psr\\Clock\\' => [$vendorDir . '/psr/clock/src'],
    'WicketAcc\\Illuminate\\Support\\' => [$vendorDir . '/illuminate/support', $vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/macroable', $vendorDir . '/illuminate/conditionable'],
    'WicketAcc\\GuzzleHttp\\Psr7\\' => [$vendorDir . '/guzzlehttp/psr7/src'],
    'WicketAcc\\GuzzleHttp\\Promise\\' => [$vendorDir . '/guzzlehttp/promises/src'],
    'WicketAcc\\GuzzleHttp\\' => [$vendorDir . '/guzzlehttp/guzzle/src'],
    'WicketAcc\\Firebase\\JWT\\' => [$vendorDir . '/firebase/php-jwt/src'],
    'WicketAcc\\Doctrine\\Inflector\\' => [$vendorDir . '/doctrine/inflector/src'],
    'WicketAcc\\Carbon\\Doctrine\\' => [$vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'],
    'WicketAcc\\Carbon\\' => [$vendorDir . '/nesbot/carbon/src/Carbon'],
    'WicketAcc\\Admin\\' => [$baseDir . '/src/admin'],
    'WicketAcc\\' => [$baseDir . '/src'],
    'Illuminate\\Contracts\\' => [$vendorDir . '/illuminate/contracts'],
    'Carbon_Fields\\' => [$vendorDir . '/htmlburger/carbon-fields/core'],
];
